### ISSUE TITLE
creation authentification

### ISSUE THREAD

**Issue by j314h** [woopears/woopr#22]
- [X] creation user
- [ ] ajouter proprieter du model user de woopear du MCD
- [x] creation auth
- [x] install lewik pour jwt
- [x] test user
- [x] test auth
- [x] test return jwt
- [x] test connexion user
- [x] creation register user
- [x] logout
- [ ] update email
- [ ] update password
- [ ] delete user
- [ ] test register
- [x] test logout
- [ ] test update email
- [ ] test update password
- [ ] test delete user
- [ ] #44

**Comment by j314h** [comment]
@OliHerz  j'ouvre un nouveau ticket pour pouvoir valider celui ci et dans le nouveau ticket je vais inclure les features d'operation courante du user, car la connexion authentification est OK.

- [ ] action sur le user model

**Comment by OliHerz** [comment]
@j314h sa marche, top merci 👍
