### ISSUE TITLE
faire la partie NOTRE ASSOCIATION

### ISSUE THREAD

**Issue by j314h** [woopears/woopr#32]
- [ ] creer les composants
- [ ] creer le store
- [ ] creer les mutations
- [ ] recuperer la data venant du back
- [ ] pense à faire une partie qui remplace le contenu initiale si la data n'existe pas coté back (pas encore creer)
- [ ] mettre loader pour chargement data

**Comment by j314h** [comment]
@OliHerz  du coup la liste ci-dessus c'est les choses qu'il reste à faire ?

**Comment by j314h** [comment]
@OliHerz ok du coup c'est la liste que j'ai fais en imaginant les choses qu'il faudrais faire.
les parties 2, 3, 4, 6 seront compliquer a faire car je suis en retard sur le back
mais le point 5 je pense tu peux le faire c'est juste un composant qui affiche un message du style pas de donnée, ou alors cette partie n'est pas encore créer ou alors en cours de construction etc.... libre à ton imagination ;-)

**Comment by OliHerz** [comment]
je peux mettre les données en brut en attendant au pire?

**Comment by j314h** [comment]
> je peux mettre les données en brut en attendant au pire?

tous a fait comme ça y aura juste à remplacer pour la suite ;-)
