### ISSUE TITLE
faire loader

### ISSUE THREAD

**Issue by j314h** [woopears/woopr#33]
- [ ] creer un loader
- [ ] #41

pour le test il doit apparaitre quand la data est en cours de chargement
et doit partir quand on reçois une réponse du back

**Comment by j314h** [comment]
@OliHerz  du coup le loader c'est une composant qu'on va afficher en attendant que la data arrive du back.
sa peux etre une roue qui tourne ou des petits points qui apparaisse disparaisse, pareil je te laisse imaginé

**Comment by OliHerz** [comment]
@j314h ok , c'est noté
